package com.education.spoonacular.entity;

import jakarta.persistence.*;
import lombok.Data;
import org.antlr.v4.runtime.BaseErrorListener;

@Data
@MappedSuperclass
public class ComponentBaseEntity extends BaseEntity {
    // unique = true in case scheme generated by Hibernate
    @Column(name = "name", nullable = false, unique = true)
    private String name;

    @Column(name = "unit", nullable = false)
    private String unit;
}
