name: Deploy Spring Boot App to EC2 via SSM

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  IMAGE_NAME: tetyana5633/spoonacular:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1   # change to your region
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy via SSM Run Command
        run: |
          INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID }}
          echo "Deploying to instance $INSTANCE_ID"

          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Spring Boot Docker app" \
            --parameters commands=$(cat <<EOF
              SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
              SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
              POSTGRES_PASSWORD=$(aws secretsmanager get-secret-value --secret-id postgres-db-password --query SecretString --output text | jq -r .postgres_password)

              docker pull $IMAGE_NAME
              docker stop spoonacular-app || true
              docker rm spoonacular-app || true
              docker run -d --name spoonacular-app -p 8080:8080 \
                -e SPRING_DATASOURCE_URL="\$SPRING_DATASOURCE_URL" \
                -e SPRING_DATASOURCE_USERNAME="\$SPRING_DATASOURCE_USERNAME" \
                -e SPRING_DATASOURCE_PASSWORD="\$POSTGRES_PASSWORD" \
                $IMAGE_NAME
            EOF
            ) \
            --output text
